# Docker compose for local development using docker.

version: '3'

services:
  app:
    build: .
    env_file: "envs/dev-docker.env"
    depends_on:
      - test

  test:
    build: .
    env_file: "envs/dev-docker.env"
    command: ["pytest", "tst"]

  redis:
    image: redis
    ports:
      - '56379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    container_name: local_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 55432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: unless-stopped
    container_name: local_minio
    ports:
      - 59000:9000
      - 59001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: 'server /data --console-address ":9001"'

volumes:
  postgres-data:
  redis-data:

